export const SUB_COURSES = {
  "B.A.": [
    "English",
    "History",
    "Sociology",
    "Economics",
    "Political Science",
    "Psychology",
    "Geography",
    "Philosophy",
    "Anthropology",
    "Linguistics",
  ],
  "B.S.": [
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Computer Science",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Astronomy",
    "Microbiology",
  ],
  "B.Ed.": [
    "Elementary Education",
    "Secondary Education",
    "Special Education",
    "Early Childhood Education",
    "Physical Education",
    "Music Education",
    "Art Education",
    "Special Needs Education",
  ],
  "B.B.A.": [
    "Finance",
    "Marketing",
    "Management",
    "Human Resources",
    "International Business",
    "Entrepreneurship",
    "Accounting",
    "Supply Chain Management",
    "Information Systems",
    "Healthcare Management",
  ],
  "B.Tech.": [
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electronics and Communication Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biotechnology",
    "Environmental Engineering",
    "Industrial Engineering",
  ],
  "B.F.A.": [
    "Painting",
    "Sculpture",
    "Graphic Design",
    "Photography",
    "Ceramics",
    "Printmaking",
    "Illustration",
    "Animation",
    "Film Production",
    "Art History",
  ],
  "B.Sc.": [
    "Nursing",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Mathematics",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Nutrition",
  ],
  "B.Com.": [
    "Accounting",
    "Finance",
    "Marketing",
    "Economics",
    "Business Management",
    "Banking and Finance",
    "Taxation",
    "Entrepreneurship",
    "Corporate Law",
    "International Business",
  ],
  "B.Arch.": [
    "Architectural Design",
    "Architectural History",
    "Urban Planning",
    "Environmental Design",
    "Landscape Architecture",
    "Building Technology",
    "Structural Engineering",
    "Interior Design",
    "Sustainable Architecture",
    "Historic Preservation",
  ],
  "M.A.": [
    "English",
    "History",
    "Sociology",
    "Economics",
    "Political Science",
    "Psychology",
    "Geography",
    "Philosophy",
    "Anthropology",
    "Linguistics",
  ],
  "M.S.": [
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Computer Science",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Astronomy",
    "Microbiology",
  ],
  "M.Ed.": [
    "Elementary Education",
    "Secondary Education",
    "Special Education",
    "Early Childhood Education",
    "Physical Education",
    "Music Education",
    "Art Education",
    "Special Needs Education",
  ],
  "M.B.A.": [
    "Finance",
    "Marketing",
    "Management",
    "Human Resources",
    "International Business",
    "Entrepreneurship",
    "Accounting",
    "Supply Chain Management",
    "Information Systems",
    "Healthcare Management",
  ],
  "M.Tech.": [
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electronics and Communication Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biotechnology",
    "Environmental Engineering",
    "Industrial Engineering",
  ],
  "M.F.A.": [
    "Painting",
    "Sculpture",
    "Graphic Design",
    "Photography",
    "Ceramics",
    "Printmaking",
    "Illustration",
    "Animation",
    "Film Production",
    "Art History",
  ],
  "M.Sc.": [
    "Nursing",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Mathematics",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Nutrition",
  ],
  "M.Com.": [
    "Accounting",
    "Finance",
    "Marketing",
    "Economics",
    "Business Management",
    "Banking and Finance",
    "Taxation",
    "Entrepreneurship",
    "Corporate Law",
    "International Business",
  ],
  "M.Arch.": [
    "Architectural Design",
    "Architectural History",
    "Urban Planning",
    "Environmental Design",
    "Landscape Architecture",
    "Building Technology",
    "Structural Engineering",
    "Interior Design",
    "Sustainable Architecture",
    "Historic Preservation",
  ],
  "M.S.W.": [
    "Clinical Social Work",
    "Community Social Work",
    "School Social Work",
    "Medical Social Work",
    "Mental Health Social Work",
    "Child and Family Social Work",
    "Substance Abuse Social Work",
    "Aging Social Work",
    "Global Social Work",
    "Military Social Work",
  ],
  "Ph.D.": [
    "English",
    "History",
    "Sociology",
    "Economics",
    "Political Science",
    "Psychology",
    "Geography",
    "Philosophy",
    "Anthropology",
    "Linguistics",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Computer Science",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Astronomy",
    "Microbiology",
    "Elementary Education",
    "Secondary Education",
    "Special Education",
    "Early Childhood Education",
    "Physical Education",
    "Music Education",
    "Art Education",
    "Special Needs Education",
    "Finance",
    "Marketing",
    "Management",
    "Human Resources",
    "International Business",
    "Entrepreneurship",
    "Accounting",
    "Supply Chain Management",
    "Information Systems",
    "Healthcare Management",
    "Computer Science and Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electronics and Communication Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biotechnology",
    "Environmental Engineering",
    "Industrial Engineering",
    "Painting",
    "Sculpture",
    "Graphic Design",
    "Photography",
    "Ceramics",
    "Printmaking",
    "Illustration",
    "Animation",
    "Film Production",
    "Art History",
    "Nursing",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Mathematics",
    "Environmental Science",
    "Geology",
    "Statistics",
    "Nutrition",
    "Accounting",
    "Finance",
    "Marketing",
    "Economics",
    "Business Management",
    "Banking and Finance",
    "Taxation",
    "Entrepreneurship",
    "Corporate Law",
    "International Business",
    "Architectural Design",
    "Architectural History",
    "Urban Planning",
    "Environmental Design",
    "Landscape Architecture",
    "Building Technology",
    "Structural Engineering",
    "Interior Design",
    "Sustainable Architecture",
    "Historic Preservation",
    "Clinical Social Work",
    "Community Social Work",
    "School Social Work",
    "Medical Social Work",
    "Mental Health Social Work",
    "Child and Family Social Work",
    "Substance Abuse Social Work",
    "Aging Social Work",
    "Global Social Work",
    "Military Social Work",
  ],
  "Ed.D.": [
    "Educational Leadership",
    "Curriculum and Instruction",
    "Educational Technology",
    "Higher Education Administration",
    "K-12 Education Administration",
    "Special Education Leadership",
    "Educational Psychology",
    "Counselor Education",
    "Adult and Lifelong Learning",
    "Educational Policy",
  ],
  "M.D.": [
    "General Medicine",
    "Surgery",
    "Pediatrics",
    "Obstetrics and Gynecology",
    "Psychiatry",
    "Anesthesiology",
    "Dermatology",
    "Radiology",
    "Emergency Medicine",
    "Neurology",
  ],
  "D.D.S.": [
    "General Dentistry",
    "Oral and Maxillofacial Surgery",
    "Orthodontics",
    "Endodontics",
    "Periodontics",
    "Pediatric Dentistry",
    "Prosthodontics",
    "Oral Pathology",
    "Dental Public Health",
    "Oral Radiology",
  ],
  "J.D.": [
    "Criminal Law",
    "Family Law",
    "Corporate Law",
    "Environmental Law",
    "Intellectual Property Law",
    "International Law",
    "Labor and Employment Law",
    "Tax Law",
    "Health Law",
    "Real Estate Law",
  ],
};
